version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocyclo
    - gosec
    - noctx
    - revive

  settings:
    govet:
      enable:
        - shadow

    gocyclo:
      min-complexity: 12

    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true
        - name: redefines-builtin-id
          disabled: true
        - name: unused-parameter
          disabled: true

  exclusions:
    generated: strict
    warn-unused: true
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - gosec
          - noctx

formatters:
  enable:
    - gofumpt
    - gci

  settings:
    gofumpt:
      extra-rules: true
      module-path: github.com/Skuyno/room-booking

    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Skuyno/room-booking)
      custom-order: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
